/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Simplified dep rules for frontend display (from tag -> [accessible tags])
 */
export interface DepRulesForDisplay {

  [key: string]: Array<string>;
}
