/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TreeNode } from '../models/tree-node';
export interface DirNode {
  children: Array<TreeNode>;
  id: string;
  isSheriffModule: boolean;
  name: string;
  pathAbs: string;
  pathRel: string;
  tags?: Array<string>;
  type: 'dir';
}
