/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PreviewContext } from '../models/preview-context';
export interface InitResponse {
  activeConfigContent: string;
  availableEntries: Array<string>;
  cwd: string;
  draft: string;
  entry: string;
  missingConfig: boolean;
  preview?: PreviewContext;
}
