/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PreviewContext } from '../models/preview-context';
export interface MutationResponse {
  draft: string;
  preview: PreviewContext;
}
