/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DepRulesForDisplay } from '../models/dep-rules-for-display';
import { DirNode } from '../models/dir-node';

/**
 * Slim preview response - contains only data needed by UI
 */
export interface PreviewContext {
  configValid: boolean;
  cwd: string;
  depRules: DepRulesForDisplay;
  errors?: Array<string>;
  tree: DirNode;
}
