/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SaveErrorResponse } from '../models/save-error-response';
import { SaveSuccessResponse } from '../models/save-success-response';
export type SaveResponse = (SaveSuccessResponse | SaveErrorResponse);

