/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MutationBase } from '../models/mutation-base';
export type ToggleDepRuleRequest = MutationBase & {
'from': string;
'to': string;
};

