/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DirNode } from '../models/dir-node';
import { FileNode } from '../models/file-node';
export type TreeNode = (DirNode | FileNode);

