/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnvResponse } from '../../models/env-response';

export interface GetEnv$Params {
}

export function getEnv(http: HttpClient, rootUrl: string, params?: GetEnv$Params, context?: HttpContext): Observable<StrictHttpResponse<EnvResponse>> {
  const rb = new RequestBuilder(rootUrl, getEnv.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnvResponse>;
    })
  );
}

getEnv.PATH = '/api/env';
