/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddTagRequest } from '../../models/add-tag-request';
import { MutationResponse } from '../../models/mutation-response';

export interface ManualAddTag$Params {
      body: AddTagRequest
}

export function manualAddTag(http: HttpClient, rootUrl: string, params: ManualAddTag$Params, context?: HttpContext): Observable<StrictHttpResponse<MutationResponse>> {
  const rb = new RequestBuilder(rootUrl, manualAddTag.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MutationResponse>;
    })
  );
}

manualAddTag.PATH = '/api/manual/add-tag';
