/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SaveRequest } from '../../models/save-request';
import { SaveResponse } from '../../models/save-response';

export interface ManualSave$Params {
      body: SaveRequest
}

export function manualSave(http: HttpClient, rootUrl: string, params: ManualSave$Params, context?: HttpContext): Observable<StrictHttpResponse<SaveResponse>> {
  const rb = new RequestBuilder(rootUrl, manualSave.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SaveResponse>;
    })
  );
}

manualSave.PATH = '/api/manual/save';
