/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MutationResponse } from '../../models/mutation-response';
import { RemoveTagRequest } from '../../models/remove-tag-request';

export interface ManualRemoveTag$Params {
      body: RemoveTagRequest
}

export function manualRemoveTag(http: HttpClient, rootUrl: string, params: ManualRemoveTag$Params, context?: HttpContext): Observable<StrictHttpResponse<MutationResponse>> {
  const rb = new RequestBuilder(rootUrl, manualRemoveTag.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MutationResponse>;
    })
  );
}

manualRemoveTag.PATH = '/api/manual/remove-tag';
