/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InitRequest } from '../../models/init-request';
import { InitResponse } from '../../models/init-response';

export interface ManualInitDefault$Params {
      body: InitRequest
}

export function manualInitDefault(http: HttpClient, rootUrl: string, params: ManualInitDefault$Params, context?: HttpContext): Observable<StrictHttpResponse<InitResponse>> {
  const rb = new RequestBuilder(rootUrl, manualInitDefault.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InitResponse>;
    })
  );
}

manualInitDefault.PATH = '/api/manual/init-default';
